version: '3.3'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - './data:/var/lib/mysql'
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8004:80
    environment:
      - PMA_ARBITRARY=1
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.5
